### ISSUE TITLE
plot doesn't work -- 'display' is not defined

### ISSUE THREAD

**Issue by ranahanocka** [conda-forge/meshplot-feedstock#6]
Issue:
When I try do a simple "hello world" example from the [geometry processing tutorial](https://geometryprocessing.github.io/geometric-computing-python/viz_basic/):

```
v, f = igl.read_triangle_mesh("data/bunny.obj")
mp.plot(v, f, v[:, 0])
```

The error I get is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rana/anaconda3/envs/geometric/lib/python3.6/site-packages/meshplot/plot.py", line 93, in plot
    display(view._renderer)
NameError: name 'display' is not defined
```

<br/>
Environment (<code>conda list</code>):
Python 3.6 , Ubuntu 16.04 with Conda Env (click for details below).
<details>

```
$ # Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py36h6f030ca_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
igl                       0.4              py36h6dc7ae4_1    conda-forge
importlib_metadata        0.23                     py36_0    conda-forge
ipydatawidgets            4.0.1                      py_0    conda-forge
ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
ipyscales                 0.3.0                      py_0    conda-forge
ipython                   7.9.0            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0           default_hde54327_4    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
markupsafe                1.1.1            py36h516909a_0    conda-forge
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h250f245_1    conda-forge
meshplot                  v0.3.2                     py_0    conda-forge
metis                     5.1.0             he1b5a44_1005    conda-forge
mistune                   0.8.4           py36h516909a_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
nspr                      4.23                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.17.3           py36h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.3.1                   py36_0    conda-forge
polyfempy                 0.5.2            py36hb914a97_2    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyqt                      5.12.3           py36hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.6           py36h516909a_0    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pythreejs                 2.1.1                      py_0    conda-forge
pyzmq                     18.1.1           py36h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.3.2            py36h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.0                   py36_0    conda-forge
six                       1.13.0                   py36_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
suitesparse               5.6.0                h717dc36_0    conda-forge
svgwrite                  1.3.1                      py_0    conda-forge
tbb                       2019.9               hc9558a2_0    conda-forge
terminado                 0.8.3                    py36_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
traittypes                0.2.1                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
wildmeshing               0.1.1            py36hbff90af_3    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$     active environment : geometric
    active env location : /home/rana/anaconda3/envs/geometric
            shell level : 2
       user config file : /home/rana/.condarc
 populated config files : /home/rana/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.0
       base environment : /home/rana/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rana/anaconda3/pkgs
                          /home/rana/.conda/pkgs
       envs directories : /home/rana/anaconda3/envs
                          /home/rana/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.4.0-98-generic ubuntu/16.04.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by Fliens** [comment]
I got the same error today :/

**Comment by horvana** [comment]
It might be late, but this did the trick for me: https://github.com/skoch9/meshplot/issues/11#issuecomment-537027376
